spring:
  main:
    banner-mode: off
sonatype:
  exclude:
    - "build-info.json"
    - "org/springframework/boot/spring-boot-docs/.*"
sdkman:
  artifact: "org.springframework.boot:spring-boot-cli:*:zip:bin"
  broadcast-url: "https://github.com/spring-projects/spring-boot/releases/v%s"
  candidate: "springboot"
